language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx opencl-headers libboost-program-options-dev libfftw3-dev
# Uncomment below to help verify the installs above work
#  - ls -la /usr/lib/libboost*
#  - ls -la /usr/include/boost

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p bin/clFFT
  - cd bin/clFFT
  - cmake -DBoost_NO_SYSTEM_PATHS=OFF -DCMAKE_INSTALL_PREFIX:PATH=$PWD/package ../../src

script: 
  - make install
#  - ls -Rla package
# Run a simple test to validate that the build works; CPU device in a VM
  - cd package/bin
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/bin/clFFT/package/lib64:${LD_LIBRARY_PATH}
  - ./clFFT-client -i

after_success:
  - cd ${TRAVIS_BUILD_DIR}/bin/clFFT
  - make package

notifications:
   email:
     - clmath-developers@googlegroups.com
   on_success: change
   on_failure: always
   